library(ROCR)
dirname<-"/home/emre/arastirma/netzcore/data/output/goh/aneurysm/"
#dirname<-commandArgs()[3] # not possible to read dirname in batch mode
postscript(paste(dirname, "compare.eps", sep=""), width = 6, height = 6, horizontal = FALSE, onefile = FALSE, paper = "special", title = "Comparison of scoring methods on aneurysm data")
v<-read.table(paste(dirname, "nz/i4/predictions.txt", sep=""))
l<-read.table(paste(dirname, "nz/i4/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
plot(perfROC, lwd=2, col=2, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=2, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.20))
v<-read.table(paste(dirname, "ns/r3i3/predictions.txt", sep=""))
l<-read.table(paste(dirname, "ns/r3i3/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
plot(perfROC, lwd=2, col=3, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=3, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.15), add=TRUE)
v<-read.table(paste(dirname, "nr/predictions.txt", sep=""))
l<-read.table(paste(dirname, "nr/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
plot(perfROC, lwd=2, col=4, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=4, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.25), add=TRUE)
v<-read.table(paste(dirname, "nd/predictions.txt", sep=""))
l<-read.table(paste(dirname, "nd/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
plot(perfROC, lwd=2, col=5, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=5, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.30), add=TRUE)
legend("bottomright", c("NetZcore", "NetScore", "NetRank", "NetShort"), lty=c(1,1,1,1), col=c(2,3,4,5))
dev.off()

