library(ROCR)
dirname<-"/home/emre/arastirma/netzcore/data/output/goh/aneurysm/"
#dirname<-commandArgs()[3] # not possible to read dirname in batch mode
postscript(paste(dirname, "compare_scoreN.eps", sep=""), width = 6, height = 6, horizontal = FALSE, onefile = FALSE, paper = "special", title = "Comparison of scoring methods on aneurysm data using GOH network")
v<-read.table(paste(dirname, "nz/i4/predictions.txt", sep=""))
l<-read.table(paste(dirname, "nz/i4/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
plot(perfROC, lwd=2, type="b", pch=19, col=2, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=2, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.20))
v<-read.table(paste(dirname, "ns/r2i4/predictions.txt", sep=""))
l<-read.table(paste(dirname, "ns/r2i4/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
plot(perfROC, lwd=2, type="b", pch=21, col=3, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=3, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.15), add=TRUE)
v<-read.table(paste(dirname, "nd/predictions.txt", sep=""))
l<-read.table(paste(dirname, "nd/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
plot(perfROC, lwd=2, type="b", pch=22, col=4, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=4, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.30), add=TRUE)
v<-read.table(paste(dirname, "nr/predictions.txt", sep=""))
l<-read.table(paste(dirname, "nr/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
#plot(perfROC, lwd=2, type="b", pch=23, col=5, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=5, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.25), add=TRUE)
v<-read.table(paste(dirname, "nw/predictions.txt", sep=""))
l<-read.table(paste(dirname, "nw/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
#plot(perfROC, lwd=2, type="b", pch=24, col=6, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=6, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.23), add=TRUE)
v<-read.table(paste(dirname, "ff/i6/predictions.txt", sep=""))
l<-read.table(paste(dirname, "ff/i6/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
#plot(perfROC, lwd=2, type="b", pch=25, col=1, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=1, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.18), add=TRUE)
v<-read.table(paste(dirname, "nx/predictions.txt", sep=""))
l<-read.table(paste(dirname, "nx/labels.txt", sep=""))
pred<-prediction(v, l)
perfROC<-performance(pred, "tpr", "fpr")
plot(perfROC, lwd=2, col=7, xlab="False Positive Rate", ylab="True Positive Rate", main="ROC curve", plotCI.col=7, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.18), add=TRUE)
#abline(0,1,lty=2)
#legend("bottomright", c("NetZcore", "NetScore", "NetShort", "ToppGene", "Seed Betw.", "FFlow", "Random"), lty=c(1,1,1,1,1,1,1), col=c(2,3,4,5,6,1,7), pch=c(19,21,22,23,24,25,0))
legend("bottomright", c("NetZcore", "NetScore", "NetShort", "Random"), lty=c(1,1,1,1), col=c(2,3,4,7), pch=c(19,21,22,0))
dev.off()

