dirname<-"../data/compare/test/"
jpeg(paste(dirname, "results.jpeg", sep=""), 648, 640)
par(mar=c(6,6,0.2,0))
e<-read.table(paste(dirname, "nr_results.dat", sep=""))
plot(e[,2], e[,1], col=2, pch=21, cex=3, xlim=c(0,0.4), ylim=c(0,1))
lines(e[,2], e[,1], col=2)
text(e[length(e[,1]),2], e[length(e[,1]),1]+0.05, col=2, "NR")
e<-read.table(paste(dirname, "ns_results.dat", sep=""))
points(e[,2], e[,1], col=6, pch=22, cex=3)
lines(e[,2], e[,1], col=6)
text(e[length(e[,1]),2], e[length(e[,1]),1]-0.05, col=6, "NS")
e<-read.table(paste(dirname, "nd_results.dat", sep=""))
points(e[,2], e[,1], col=4, pch=23, cex=3)
lines(e[,2], e[,1], col=4)
text(e[length(e[,1]),2], e[length(e[,1]),1]-0.05, col=4, "ND")
e<-read.table(paste(dirname, "nz_results.dat", sep=""))
points(e[,2], e[,1], col=5, pch=24, cex=3)
lines(e[,2], e[,1], col=5)
text(e[length(e[,1]),2], e[length(e[,1]),1]-0.05, col=5, "NZ")
e<-read.table(paste(dirname, "ff_results.dat", sep=""))
points(e[,2], e[,1], col=3, pch=25, cex=3)
lines(e[,2], e[,1], col=3)
text(e[length(e[,1]),2], e[length(e[,1]),1]+0.05, col=3, "FF")
#plot(e[1:2,2], e[1:2,1], col=2, pch="o", xlim=c(0,1), ylim=c(0,1))
#text(e[,2], e[,1], row.names(e))
dev.off()

