library(ROCR)
v<-read.table("netzcore_it_predictions.txt")
l<-read.table("netzcore_it_labels.txt")
pred<-prediction(v, l)
perfNetZcore_it<-performance(pred, "tpr", "fpr")

v<-read.table("netzcore_sq_it_predictions.txt")
l<-read.table("netzcore_sq_it_labels.txt")
pred<-prediction(v, l)
perfNetZcore_sq_it<-performance(pred, "tpr", "fpr")

v<-read.table("../functionalFlow_predictions_n5_e0.001.txt")
l<-read.table("../functionalFlow_labels_n5_e0.001.txt")
pred<-prediction(v, l)
perfFFlow<-performance(pred, "tpr", "fpr")

plot(perfNetZcore_it, lwd=2, col=2, plotCI.col=2, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.20))
plot(perfNetZcore_sq_it, lwd=2, col=4, plotCI.col=4, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.33), add=TRUE)
plot(perfFFlow, lwd=2, col=3, plotCI.col=3, avg="vertical", spread.estimate="stddev", show.spread.at=seq(0,1,by=0.25), add=TRUE)
legend("topright", c("NetZcore_it", "NetZcore_sq_it", "FFlow"), lty=c(1,1,1), col=c(2,4,3))
